server:
  port: 8086
  servlet:
    context-path: /github
spring:
  application:
    name: Github-trigger
  boot:
    admin:
      client:
        url: http://47.100.253.25:8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always