server:
  port: 8086
  servlet:
    context-path: /github
spring:
  application:
    name: github-trigger
  boot:
    admin:
      client:
        url: http://47.100.253.25:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
